# Generated by Django 2.1.1 on 2018-10-09 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=256)),
                ('room_id', models.CharField(max_length=256)),
                ('read_num', models.IntegerField(default=0)),
            ],
        ),
    ]
