# Generated by Django 2.1.1 on 2018-10-09 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField()),
                ('introduce', models.TextField()),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('company_logo', models.ImageField(blank=True, default='CompanLogo/default.png', upload_to='CompanLogo')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField()),
                ('introduce', models.TextField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='introduce.CompanyInfo')),
            ],
        ),
    ]
